[project]
name = 'boost-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Badge-revocation]
path = 'contracts/Badge-revocation.clar'
clarity_version = 3
epoch = 3.0

[contracts.badge-minting]
path = 'contracts/badge-minting.clar'
clarity_version = 3
epoch = 3.0

[contracts.badge-verification]
path = 'contracts/badge-verification.clar'
clarity_version = 3
epoch = 3.0

[contracts.badge-wallet]
path = 'contracts/badge-wallet.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
